fwb: interceptScreenshotChord method changes feature dependent: 	- threefinger ss
*frameworks/base/services/core/java/com/android/server/policy/PhoneWindowManager.java:2072: error: method interceptScreenshotChord in class PhoneWindowManager cannot be applied to given types;
                interceptScreenshotChord(
                ^
  required: int,long
  found: int,int,int
  reason: actual and formal argument lists differ in length

Signed-off-by: escobar1945 <candaroglu197878@gmail.com>